name: Deploy
on:
  workflow_dispatch:
  push:
    branch:
      - main
    paths-ignore: # 下列文件的变更不触发部署
      - .vscode
      - .gitignore
      - eslint.config.js
      - README.md
  repository_dispatch:
    types: rebuild

jobs:
  main-branch-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SECRETS_HOST }}
          port: ${{ secrets.SECRETS_PORT }}
          username: ${{ secrets.SECRETS_USERNAME }}
          password: ${{ secrets.SECRETS_PASSWORD }}
          script: |
            cd /opt/cxs/md
            git pull origin main
            pnpm install
            pnpm build